# Generated by Django 4.2.7 on 2024-07-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Cement', 'Cement'), ('Bricks', 'Bricks'), ('Tools', 'Tools'), ('Paint', 'Paint'), ('Sand', 'Sand')], max_length=50, null=True),
        ),
    ]
